main_page_link = 'http://selenium1py.pythonanywhere.com/ru'
new_email = 'not_me@mail.ru'
email = 'its_me@mail.ru'
password = 'nekakuvseh123'
login_link = 'a#login_link'
input_email = 'input#id_registration-email'
input_password = 'input#id_registration-password1'
input_repeat_password = 'input#id_registration-password2'
button_reg = 'button[value="Register"]'
input_search = 'input#id_q'
input_search_button = 'input[value = "Найти"]'
