main_page_link = 'http://selenium1py.pythonanywhere.com'
login_link = 'a#login_link'
input_email = 'input#id_registration-email'
input_password = 'input#id_registration-password1'
input_repeat_password = 'input#id_registration-password2'
button_reg = 'button[value="Register"]'
input_search = 'input#id_q'
input_search_button = 'input[value = "Найти"]'
input_email_auth = 'input#id_login-username'
input_password_auth = 'input#id_login-password'
button_auth = 'button[value="Log In"]'
reset_password = 'a[href="/ru/password-reset/"]'
button_to_order = 'a[href="/ru/checkout/"]'
input_name = 'input#id_first_name'
input_lastname = 'input#id_last_name'
input_address = 'input#id_line1'
input_city = 'input#id_line4'
input_postcode = 'input#id_postcode'
button_to_continue = '//button[contains(text(), "Продолжить")]'
catalog_link = '//*[@id="browse"]/li/ul/li[1]/a'
book_locator = 'a[title="Coders at Work"]'
button_add_to_cart = '//*[@id="add_to_basket_form"]/button'
button_view_cart = 'a[href="/ru/basket/"]'
link_to_payment = 'a#view_preview'
input_remind_password = 'input#id_email'
button_reset_password = '//button[contains(text(), "Отправить письмо для смены пароля")]'
catalog_heading = 'Все товары'
catalog_heading_locator = 'div.page-header.action h1'
success_message = 'Рады видеть вас снова'
success_message_locator = '//div[contains(text(), "Рады видеть вас снова")]'
