# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegistration():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registration(self):
    # Test name: Registration
    # Step # | name | target | value
    # 1 | open | /fr/ | 
    self.driver.get("http://selenium1py.pythonanywhere.com/fr/")
    # 2 | setWindowSize | 1359x800 | 
    self.driver.set_window_size(1359, 800)
    # 3 | click | id=login_link | 
    self.driver.find_element(By.ID, "login_link").click()
    # 4 | click | id=id_registration-email | 
    self.driver.find_element(By.ID, "id_registration-email").click()
    # 5 | type | id=id_registration-email | lol@mail.ru
    self.driver.find_element(By.ID, "id_registration-email").send_keys("lol@mail.ru")
    # 6 | click | id=id_registration-password1 | 
    self.driver.find_element(By.ID, "id_registration-password1").click()
    # 7 | type | id=id_registration-password1 | 5432112345
    self.driver.find_element(By.ID, "id_registration-password1").send_keys("5432112345")
    # 8 | click | id=id_registration-password2 | 
    self.driver.find_element(By.ID, "id_registration-password2").click()
    # 9 | type | id=id_registration-password2 | 5432112345
    self.driver.find_element(By.ID, "id_registration-password2").send_keys("5432112345")
    # 10 | click | name=registration_submit | 
    self.driver.find_element(By.NAME, "registration_submit").click()
  
